const mediaActionTypes ={
    MEDIA_DETAILS_REQUEST: 'MEDIA_DETAILS_REQUEST',
    MEDIA_DETAILS_SUCCESS: 'MEDIA_DETAILS_SUCESS',
    MEDIA_DETAILS_FAILURE: 'MEDIA_DETAILS_FAILURE',
}

export default mediaActionTypes